const intakeEntryTemplateMap = {
    "First Name":                                                                                                                                          "",
    "Last Name":                                                                                                                                           "",
    "Date of Birth":                                                                                                                                       "DOB",
    "What has prompted the evaluation at this time?":                                                                                                      "",
    "What do you hope to gain from a neuropsychological assessment?":                                                                                      "",
    "Describe the patient's current living situation.":                                                                                                    "Living Situation",
    "Gender Identity":                                                                                                                                     "",
    "Pronouns":                                                                                                                                            "",
    "Sexual Orientation":                                                                                                                                  "",
    "Where was the patient born?":                                                                                                                         "",
    "Where was the patient raised?":                                                                                                                       "",
    "Did you move as a child? If so, at what age?":                                                                                                        "",
    "Maternal History":                                                                                                                                    "",
    "Paternal History":                                                                                                                                    "",
    "Please describe any important cultural history and ethnic identity of the patient.":                                                                  "Cultural heritage",
    "Gestation":                                                                                                                                           "",
    "Delivery":                                                                                                                                            "",
    "Did the patient see their doctor or pediatrician for annual well child checkups?":                                                                    "",
    "Describe gross motor development":                                                                                                                    "",
    "Describe fine motor development":                                                                                                                     "",
    "Describe speech and communication development":                                                                                                       "",
    "Please describe how discipline or consequences are handled in the home. Is one caregiver typically the disciplinarian? Are caregivers in agreement?": "",
    "Sensory processing concerns?":                                                                                                                        "",
    "Any developmental regression?":                                                                                                                       "",
    "When did the patient start structured education.":                                                                                                    "",
    "Please list all schools, grades attended.":                                                                                                           "Please list all schools and grades attended",
    "What is the patient's highest level of education?":                                                                                                   "Highest Level of Education",
    "Where did they attend school for the highest level of education?":                                                                                    "Highest Level of Education Location",
    "Please note any concerns in any grades. ":                                                                                                            "",
    "Has the patient ever repeated a grade?":                                                                                                              "",
    "Special accommodations?":                                                                                                                             "Special Accommodations",
    "Any diagnoses for learning disorders or ADHD?":                                                                                                       "",
    "Any problems at school?":                                                                                                                             "",
    "What are current hobbies or activities?":                                                                                                             "",
    "Please note if there is any significant medical history.":                                                                                            "",
    "Any emergency room visits?":                                                                                                                          "",
    "Any surgeries?":                                                                                                                                      "",
    "Please elaborate about anything noted above.":                                                                                                        "",
    "Any head injury?":                                                                                                                                    "",
    "Specify all medications and supplements presently taking with the dosage and the reason.":                                                            "",
    "If taking prescription medication, who is the prescribing provider?":                                                                                 "",
    "Who is the patient's primary care physician?":                                                                                                        "",
    "Allergies?":                                                                                                                                          "",
    "Immunizations up to date?":                                                                                                                           "",
    "Are other substances, such as caffeine, tobacco, marijuana, or other non prescription or recreational drugs used?":                                   "",
    "Sleep Concerns?":                                                                                                                                     "",
    "Appetite":                                                                                                                                            "",
    "Vision Concerns?":                                                                                                                                    "",
    "Hearing Concerns?":                                                                                                                                   "",
    "Does the patient have a psychiatric diagnosis?":                                                                                                      "",
    "Has the patient ever been hospitalized for a psychiatric issue?":                                                                                     "",
    "Does the patient currently see a therapist or have seen one in the past?":                                                                            "",
    "Is there a history of mental illness in the family?":                                                                                                 "",
    "Anxiety":                                                                                                                                             "",
    "Somatic Complaints":                                                                                                                                  "",
    "Worry":                                                                                                                                               "",
    "Fear":                                                                                                                                                "",
    "Appropriate Stranger Danger":                                                                                                                         "",
    "Risk/Danger awareness":                                                                                                                               "",
    "Obsessive Thoughts":                                                                                                                                  "",
    "Repetitive Behaviors or Habits":                                                                                                                      "",
    "Depressed Mood":                                                                                                                                      "",
    "Impulsivity":                                                                                                                                         "",
    "Hyperactivity":                                                                                                                                       "",
    "Distractibility":                                                                                                                                     "",
    "Inattention":                                                                                                                                         "",
    "Tantrums":                                                                                                                                            "",
    "Self-Injurious Behaviors":                                                                                                                            "",
    "Aggression":                                                                                                                                          "",
    "Hallucinations/Delusions":                                                                                                                            "",
    "Substance Use":                                                                                                                                       "",
    "Sexual History":                                                                                                                                      "",
    "Social Connections":                                                                                                                                  "",
    "Please describe social supports.":                                                                                                                    "Social Supports",
    "If in a relationship, please describe the nature of the relationship and length of time together.":                                                   "",
    "Does the patient feel safe in the relationship?":                                                                                                     "",
    "Please check any of the following that apply":                                                                                                        "",
    "History of Abuse or Neglect?":                                                                                                                        "",
    "Any CPS Contact?":                                                                                                                                    "",
    "Any history or Interaction with Legal System/Legal Concerns?":                                                                                        "History with Legal System or Legal Concerns",
    "Please note the patient's strengths.":                                                                                                                "",
    "Is there anything else that you would like me to know?":                                                                                              "",
}

// Fill in blank values with equivalent strings to the corresponding key
for (const key in intakeEntryTemplateMap) {
    if (intakeEntryTemplateMap[key] === "") {
        intakeEntryTemplateMap[key] = key;
    }
}
